### ISSUE TITLE
Feature request: custom font style for title and description

### ISSUE THREAD

**Issue by MohamadKh75** [seniv/react-native-notifier#13]
Hey

Thanks for your great lib! It's awesome :heart:
I just want to change the title and description style. I know there is a way to render `CustomComponent` but I guess it's overworking!

I created a PR and hope you don't prefer the `CustomComponent` way :grin:

**Comment by seniv** [comment]
Hey @MohamadKh75, thanks for the PR!
This makes sense. I didn't add the ability to customize Components from the beginning only because I thought that most people will not use the default components and create their own components 😄

I'll also add the ability to pass `Image` styles of the `Notification` component.

**Comment by MohamadKh75** [comment]
Great!
And when do we have a release :grin: ?

**Comment by seniv** [comment]
In a couple of minutes, I'm finishing the `imageStyle` param)

BTW, I updated the docs from your PR for a little bit here: https://github.com/seniv/react-native-notifier/commit/a3e92b806ae621f7ac3c4a2bb975987eaed0c881
Because `title/descriptionStyle` will work only as `componentProps`

**Comment by seniv** [comment]
Done, 1.3.0 is released🙂

**Comment by MohamadKh75** [comment]
Tnx :rocket:
