### ISSUE TITLE
Feature: support of message id so a similar notification just replaces the current one

### ISSUE THREAD

**Issue by pke** [seniv/react-native-notifier#55]
It would be nice if we could have an "id" associated with a message, that will then lead to the current notification with the same id to just change its content and play a little wiggle animation (or pulse or something).

**Comment by seniv** [comment]
Hey @pke, can you provide a use-case where this feature can be useful?
Since this library can display only one notification per time, I think it will be enough to have something like `updateCurrentNoficiation` method. But I might be wrong, and that's why I need to know how you are planning to use it  🙂
